version: '3.8'

services:
  # Laravel application service with Apache
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app_new
    restart: unless-stopped
    volumes:
      - .:/var/www/html # Keep this mount for your application code
      # REMOVE THIS LINE: - ./apache.conf:/etc/apache2/sites-available/laravel.conf
    ports:
      - "80:80"
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel_network

  # MySQL database service (no changes needed here)
  db:
    image: mysql:8.0
    container_name: laravel_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: users
      MYSQL_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

# Define Docker volumes for data persistence
volumes:
  db_data:

# Define Docker networks for inter-container communication
networks:
  laravel_network:
    driver: bridge